from selenium.webdriver.common.by import By
from src.test.common.page import Page
import time

class quotationmanagementpage(Page):
    Seller_Center = (By.XPATH,'/html/body/div/div/div/div[1]/div/div[2]/div[2]/span[1]')
    Quotation_management = (By.XPATH,'/html/body/div/div/div/section/div[2]/div/div/div[1]/div/div[2]/div/ul/li[2]/ul/li[2]')
    Inquiry_No_input = (By.XPATH,'/html/body/div/div/div/section/div[2]/div/div/div[2]/div/div/div/div[3]/div/div[1]/form/div[1]/div/div/div/input')
    query = (By.ID,'queryBtn')
    To_quote = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div/div[4]/div[2]/div[1]/div[4]/div[2]/table/tbody/tr/td[9]/div/a/span')
    Warehouse = (By.XPATH,'//*[@id="priceBox"]/div[2]/div[2]/div[1]/form/div[1]/div/div/div/div[1]/input')
    Warehouse_click = (By.XPATH,'/html/body/div[2]/div[1]/div[1]/ul/div[1]/li/span')
    Place_of_Origin_1 = (By.XPATH,'//*[@id="priceBox"]/div[2]/div[2]/div[1]/form/div[2]/div/div/div/div/input')
    Place_of_Origin_click = (By.XPATH,'/html/body/div[2]/div[1]/div[1]/ul/div[1]/li')
    quantity = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div[1]/div[3]/div[2]/div[2]/div[1]/form/div[3]/div/div/div/div/input')
    weight = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div[1]/div[3]/div[2]/div[2]/div[1]/form/div[4]/div/div/div/div/input')
    Quotation_amount = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div[1]/div[3]/div[2]/div[2]/div[1]/form/div[5]/div/div[1]/div/div/input')
    Submit_quotation = (By.ID,'subBtn')
    one_touch = (By.XPATH,'//*[@id="addResourceRef"]/div/div[3]/span/div[2]/button[2]/span')
    determine = (By.XPATH,'//*[@id="dialog"]/div/div[3]/span/button[2]')
    Modify_quotation = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div/div[4]/div[2]/div[1]/div[4]/div[2]/table/tbody/tr/td[9]/div/a[1]/span')

    #单条明细
    Place_of_Origin_2 = (By.XPATH,'//*[@id="priceBox"]/div[2]/div[2]/div/form/div[2]/div/div/div/div/input')
    click = (By.XPATH,'//*[@id="infoBox"]/div[1]')
    def quotationmanagement(self,Inquiry_No,si,pi,qi,wi,qui):
        '''询单报价'''
        time.sleep(3)
        self.find_element(*self.Seller_Center).click()
        time.sleep(1)
        self.find_element(*self.Quotation_management).click()
        time.sleep(1)
        self.find_element(*self.Inquiry_No_input).click()
        time.sleep(1)
        self.find_element(*self.Inquiry_No_input).send_keys(Inquiry_No)
        time.sleep(1)
        self.find_element(*self.query).click()
        time.sleep(1)
        self.find_element(*self.To_quote).click()
        time.sleep(1)
        self.find_element(*self.Warehouse).send_keys(si)
        time.sleep(2)
        self.find_element(*self.Warehouse_click).click()
        time.sleep(1)
        try:
            self.find_element(*self.Place_of_Origin_2).send_keys(pi)
        except:
            self.find_element(*self.Place_of_Origin_1).send_keys(pi)
        time.sleep(2)
        self.find_element(*self.Place_of_Origin_click).click()
        time.sleep(1)
        self.find_element(*self.quantity).clear()
        time.sleep(1)
        self.find_element(*self.quantity).send_keys(qi)
        time.sleep(1)
        self.find_element(*self.weight).clear()
        time.sleep(1)
        self.find_element(*self.weight).send_keys(wi)
        time.sleep(1)
        self.find_element(*self.Quotation_amount).clear()
        time.sleep(1)
        self.find_element(*self.Quotation_amount).send_keys(qui)
        time.sleep(1)
        self.find_element(*self.Submit_quotation).click()
        time.sleep(1)
        self.find_element(*self.one_touch).click()
        time.sleep(1)
        self.find_element(*self.Submit_quotation).click()
        time.sleep(1)
        self.find_element(*self.determine).click()
        time.sleep(2)

    def Modifyquotation(self,Inquiry_No,qui_a):
        '''修改报价'''
        # time.sleep(3)
        # self.find_element(*self.Seller_Center).click()
        # time.sleep(1)
        # self.find_element(*self.Quotation_management).click()
        # time.sleep(1)
        self.find_element(*self.Inquiry_No_input).send_keys(Inquiry_No)
        time.sleep(1)
        self.find_element(*self.query).click()
        time.sleep(1)
        self.find_element(*self.Modify_quotation).click()
        time.sleep(1)
        self.find_element(*self.Quotation_amount).click()
        self.find_element(*self.Quotation_amount).click()
        self.find_element(*self.Quotation_amount).click()
        self.find_element(*self.Quotation_amount).send_keys(qui_a)
        time.sleep(1)
        self.find_element(*self.Submit_quotation).click()
        time.sleep(1)
        self.find_element(*self.determine).click()
        time.sleep(2)


    def quotationmanagement_a(self,Inquiry_No,pi,qui):
        '''虚单报价'''
        time.sleep(3)
        self.find_element(*self.Seller_Center).click()
        time.sleep(1)
        self.find_element(*self.Quotation_management).click()
        time.sleep(1)
        self.find_element(*self.Inquiry_No_input).send_keys(Inquiry_No)
        time.sleep(1)
        self.find_element(*self.query).click()
        time.sleep(1)
        self.find_element(*self.To_quote).click()
        time.sleep(1)
        try:
            self.find_element(*self.Place_of_Origin_2).send_keys(pi)
        except:
            self.find_element(*self.Place_of_Origin_1).send_keys(pi)
        time.sleep(2)
        self.find_element(*self.Place_of_Origin_click).click()
        time.sleep(1)
        self.find_element(*self.Quotation_amount).clear()
        time.sleep(1)
        self.find_element(*self.Quotation_amount).send_keys(qui)
        time.sleep(1)
        self.find_element(*self.Submit_quotation).click()
        time.sleep(1)
        self.find_element(*self.determine).click()
        time.sleep(2)

    def Improve_quotation(self,Inquiry_No,si,qi,wi):
        '''完善报价'''
        time.sleep(3)
        self.find_element(*self.Seller_Center).click()
        time.sleep(1)
        self.find_element(*self.Quotation_management).click()
        time.sleep(1)
        self.find_element(*self.Inquiry_No_input).send_keys(Inquiry_No)
        time.sleep(1)
        self.find_element(*self.query).click()
        time.sleep(1)
        self.find_element(*self.To_quote).click()
        time.sleep(1)
        self.find_element(*self.Warehouse).send_keys(si)
        time.sleep(2)
        self.find_element(*self.Warehouse_click).click()
        time.sleep(1)
        self.find_element(*self.quantity).clear()
        time.sleep(1)
        self.find_element(*self.quantity).send_keys(qi)
        time.sleep(2)
        self.find_element(*self.click).click()
        time.sleep(1)
        try:
            self.find_element(*self.weight).clear()
            time.sleep(1)
            self.find_element(*self.weight).send_keys(wi)
            time.sleep(1)
        except:
            self.find_element(*self.Submit_quotation).click()
            time.sleep(1)
            self.find_element(*self.determine).click()
            time.sleep(2)