from selenium.webdriver.common.by import By
from src.test.common.page import Page
import time

class Resourceuploadpage(Page):
    # home_page_url = 'http://test-xc.ouyeel.com/isssp-portal-ng/'
    #识别上传
    seller_Center = (By.XPATH,'/html/body/div/div/div/div[1]/div/div[2]/div[2]/span[1]')
    upload_Center = (By.XPATH,'//*[@id="__layout"]/div/section/div[2]/div/div/div[1]/div/div[2]/div/ul/li[3]/ul/li[1]')
    text_input = (By.XPATH,'//*[@id="__layout"]/div/section/div[2]/div/div/div[2]/div/div/div[2]/div[2]/div[1]/div[2]/div[2]/div/textarea')
    intelligent_identification = (By.XPATH,'//*[@id="__layout"]/div/section/div[2]/div/div/div[2]/div/div/div[2]/div[2]/div[1]/div[2]/div[1]/div/button[2]/span')
    specification_span = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[6]/div/span')
    specification_input = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[6]/div/div/div/div/input')
    specification_selection_a = (By.XPATH,'/html/body/div[5]/div[1]/div[1]/ul/div[1]/li/span')
    specification_selection= (By.XPATH,'/html/body/div[3]/div[1]/div[1]/ul/li/span')
    identify_resources = (By.ID,'confirmBtn')
    one_touch = (By.XPATH,'//*[@id="addResourceRef"]/div/div[3]/span/div[2]/button[2]')

    #手动上传
    Add_a_new_line = (By.ID,'addBtn')
    varieties_input = (By.XPATH,'/html/body/div/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[3]/div/span')
    varieties_input_a = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[3]/div/div/div/div/input')
    varieties_choice = (By.XPATH,'/html/body/div[2]/div[1]/div[1]/ul/div[1]/li[1]')
    Place_of_Origin_input = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[4]/div/div/div/div[1]/input')
    Place_of_Origin_choice = (By.XPATH,'/html/body/div[3]/div[1]/div[1]/ul/div[1]/li')
    Brand_input = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[5]/div/div/div/div/input')
    Brand_choice = (By.XPATH,'/html/body/div[4]/div[1]/div[1]/ul/div[1]/li[1]/span')
    length = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[7]/div/div/div[1]/div/input')
    quantity = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[9]/div/div/div/div/input')
    Total_weight = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[11]/div/div/div[1]/div/input')
    Warehouse_input = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[12]/div/div/div/div[1]/input')
    Warehouse_choice = (By.XPATH,'/html/body/div[6]/div[1]/div[1]/ul/div[1]/li')
    Price = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[13]/div/div/div/div/input')
    technical_standard_input = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[15]/div/div/div/div[1]/input')
    technical_standard_choice = (By.XPATH,'/html/body/div[7]/div[1]/div[1]/ul/div[1]/li')

    def Resourceupload(self,ti,si):
        '''资源上传'''
        time.sleep(3)
        self.find_element(*self.seller_Center).click()
        time.sleep(1)
        self.find_element(*self.upload_Center).click()
        time.sleep(1)
        self.find_element(*self.text_input).send_keys(ti)
        time.sleep(1)
        self.find_element(*self.intelligent_identification).click()
        time.sleep(2)
        self.find_element(*self.specification_span).click()
        time.sleep(1)
        self.find_element(*self.specification_input).send_keys(si)
        time.sleep(2)
        self.find_element(*self.specification_selection).click()
        time.sleep(1)
        self.find_element(*self.identify_resources).click()
        time.sleep(2)
        # self.find_element(*self.one_touch).click()
        # time.sleep(2)
        # self.find_element(*self.identify_resources).click()
        # time.sleep(2)

    def Manualresourceupload(self,vi,pi,bi,si,li,qi,ti,wi,pa,ta):
        '''手动资源上传'''
        self.driver.refresh()
        time.sleep(3)
        self.find_element(*self.seller_Center).click()
        self.find_element(*self.upload_Center).click()
        time.sleep(1)
        self.find_element(*self.Add_a_new_line).click()
        time.sleep(2)
        self.find_element(*self.varieties_input).click()
        time.sleep(1)
        self.find_element(*self.varieties_input_a).send_keys(vi)
        time.sleep(2)
        self.find_element(*self.varieties_choice).click()
        time.sleep(1)
        self.find_element(*self.Place_of_Origin_input).send_keys(pi)
        time.sleep(2)
        self.find_element(*self.Place_of_Origin_choice).click()
        time.sleep(1)
        self.find_element(*self.Brand_input).send_keys(bi)
        time.sleep(3)
        self.find_element(*self.Brand_choice).click()
        time.sleep(1)
        self.find_element(*self.specification_input).send_keys(si)
        time.sleep(2)
        self.find_element(*self.specification_selection_a).click()
        time.sleep(1)
        self.find_element(*self.length).clear()
        time.sleep(1)
        self.find_element(*self.length).click()
        time.sleep(1)
        self.find_element(*self.length).send_keys(li)
        time.sleep(1)
        self.find_element(*self.quantity).clear()
        time.sleep(2)
        self.find_element(*self.quantity).send_keys(qi)
        time.sleep(1)
        self.find_element(*self.Total_weight).clear()
        time.sleep(2)
        self.find_element(*self.Total_weight).send_keys(ti)
        time.sleep(2)
        self.find_element(*self.Warehouse_input).send_keys(wi)
        time.sleep(2)
        self.find_element(*self.Warehouse_choice).click()
        time.sleep(1)
        self.find_element(*self.Price).clear()
        time.sleep(2)
        self.find_element(*self.Price).send_keys(pa)
        time.sleep(2)
        self.find_element(*self.technical_standard_input).send_keys(ta)
        time.sleep(2)
        self.find_element(*self.technical_standard_choice).click()
        time.sleep(1)
        self.find_element(*self.identify_resources).click()
        time.sleep(2)
