from selenium.webdriver.common.by import By
from src.test.common.page import Page
import time

class InquiryUploadpage(Page):
    #询单上传识别操作
    Buyer_Center = (By.XPATH,'/html/body/div/div/div/div[1]/div/div[2]/div[1]/span[1]')
    Inquiry_Upload = (By.XPATH,'/html/body/div/div/div/section/div[2]/div/div/div[1]/div/div[2]/div/ul/li[2]/ul/li[1]')
    Text_input = (By.XPATH,'/html/body/div/div/div/section/div[2]/div/div/div[2]/div/div/div[2]/div[2]/div[1]/div[2]/div[2]/div/textarea')
    Intelligent_identification = (By.ID,'readBtn')
    Specifications = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[5]/div/span')
    Specifications_input = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[5]/div/div/div/div/input')
    Specifications_click = (By.XPATH,'/html/body/div[3]/div[1]/div[1]/ul/li/span')
    Place_of_delivery = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[12]/div/div/input')
    Tolerance_range = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[15]/div/div/input')
    copy = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div[2]/div[1]/div[5]/div[2]/div/div/table/tbody/tr/td/div/a[1]/span')
    Designated_supplier = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[1]/div[2]/div[2]/form/div[1]/div/div/div[1]/label[2]/span[2]/span')
    supplier_input = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[5]/div/div[2]/div[2]/div[1]/div/div[1]/input')
    Select_All = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[5]/div/div[2]/div[2]/div[1]/p/label/span[1]/span')
    move = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[5]/div/div[2]/div[2]/div[2]/button[2]')
    preservation = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[5]/div/div[3]/span/button[1]')
    determine = (By.ID,'publishInfoBtn')

    #询单上传手动操作
    Add_a_new_line = (By.ID,'addBtn')
    Inquiry_type = (By.XPATH,'/html/body/div/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[1]/div[2]/form/div[2]/div/div/div/label[2]/span[1]/span')
    varieties_click = (By.XPATH,'/html/body/div/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[3]/div/span')
    varieties_input = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[3]/div/div/div/div/input')
    varieties_choice = (By.XPATH,'/html/body/div[2]/div[1]/div[1]/ul/div[1]/li[1]')
    Brand_input = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[4]/div/div/div/div[1]/input')
    Brand_choice = (By.XPATH,'/html/body/div[3]/div[1]/div[1]/ul/div[1]/li[10]/span')
    Specifications_click_a = (By.XPATH,'/html/body/div[4]/div[1]/div[1]/ul/div[1]/li/span')
    quantity = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[9]/div/div/div/div/input')
    weight = (By.XPATH,'//*[@id="uploadTableRef"]/div[1]/div[3]/div/div/table/tbody/tr/td[11]/div/div/div[1]/div/input')
    Place_of_Origin_input = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[7]/div/div/div/div[2]/input')
    Place_of_Origin_choice = (By.XPATH,'/html/body/div[5]/div[1]/div[1]/ul/div[1]/li/span')
    Place_of_delivery_input = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[12]/div/div/input')
    technical_standard_input = (By.XPATH,'/html/body/div[1]/div/div/section/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div[2]/div[1]/div[3]/div/div/table/tbody/tr/td[14]/div/div/div/div[1]/input')
    technical_standard_choice = (By.XPATH,'/html/body/div[6]/div[1]/div[1]/ul/div[1]/li/span')


    def Character_recognition(self,ti,gi,pi):
        '''询单上传（文字识别）'''
        time.sleep(3)
        self.find_element(*self.Buyer_Center).click()
        time.sleep(1)
        self.find_element(*self.Inquiry_Upload).click()
        time.sleep(1)
        self.find_element(*self.Text_input).send_keys(ti)
        time.sleep(1)
        self.find_element(*self.Intelligent_identification).click()
        time.sleep(1)
        self.find_element(*self.Specifications).click()
        time.sleep(1)
        self.find_element(*self.Specifications_input).send_keys(gi)
        time.sleep(2)
        self.find_element(*self.Specifications_click).click()
        time.sleep(1)
        self.find_element(*self.Place_of_delivery).send_keys(pi)
        time.sleep(1)
        self.find_element(*self.Tolerance_range).clear()
        time.sleep(2)
        self.find_element(*self.copy).click()
        time.sleep(1)
        # self.find_element(*self.Designated_supplier).click()
        # time.sleep(1)
        # self.find_element(*self.supplier_input).send_keys(si)
        # time.sleep(2)
        # self.find_element(*self.Select_All).click()
        # time.sleep(1)
        # self.find_element(*self.move).click()
        # time.sleep(1)
        # self.find_element(*self.preservation).click()
        # time.sleep(1)
        self.find_element(*self.determine).click()
        time.sleep(2)
    
    def Character_recognition_a(self,ti,gi,pi):
        '''询单专区测试前置条件'''
        self.driver.refresh()
        time.sleep(3)
        self.find_element(*self.Buyer_Center).click()
        time.sleep(1)
        self.find_element(*self.Inquiry_Upload).click()
        time.sleep(1)
        self.driver.refresh()
        self.find_element(*self.Inquiry_type).click()
        time.sleep(1)
        self.find_element(*self.Text_input).send_keys(ti)
        time.sleep(1)
        self.find_element(*self.Intelligent_identification).click()
        time.sleep(1)
        self.find_element(*self.Specifications).click()
        time.sleep(1)
        self.find_element(*self.Specifications_input).send_keys(gi)
        time.sleep(2)
        self.find_element(*self.Specifications_click).click()
        time.sleep(1)
        self.find_element(*self.Place_of_delivery).send_keys(pi)
        time.sleep(1)
        self.find_element(*self.Tolerance_range).clear()
        time.sleep(2)
        self.find_element(*self.determine).click()
        time.sleep(2)

    def Character_recognition_Manual(self,vi,bi,si,pi,pi_a,ti,qi,wi):
        '''询单上传手动'''
        time.sleep(3)
        self.find_element(*self.Buyer_Center).click()
        time.sleep(1)
        self.find_element(*self.Inquiry_Upload).click()
        time.sleep(1)
        self.find_element(*self.Inquiry_type).click()
        time.sleep(1)
        self.find_element(*self.Add_a_new_line).click()
        time.sleep(1)
        self.find_element(*self.varieties_click).click()
        time.sleep(1)
        self.find_element(*self.varieties_input).send_keys(vi)
        time.sleep(2)
        self.find_element(*self.varieties_choice).click()
        time.sleep(1)
        self.find_element(*self.Brand_input).send_keys(bi)
        time.sleep(2)
        self.find_element(*self.Brand_choice).click()
        time.sleep(1)
        self.find_element(*self.Specifications_input).send_keys(si)
        time.sleep(2)
        self.find_element(*self.Specifications_click_a).click()
        time.sleep(1)
        self.find_element(*self.Place_of_Origin_input).send_keys(pi)
        time.sleep(2)
        self.find_element(*self.Place_of_Origin_choice).click()
        time.sleep(1)
        self.find_element(*self.quantity).clear()
        time.sleep(1)
        self.find_element(*self.quantity).send_keys(qi)
        time.sleep(1)
        self.find_element(*self.weight).clear()
        time.sleep(1)
        self.find_element(*self.weight).send_keys(wi)
        time.sleep(1)
        self.find_element(*self.Place_of_delivery_input).send_keys(pi_a)
        time.sleep(1)
        self.find_element(*self.technical_standard_input).send_keys(ti)
        time.sleep(2)
        self.find_element(*self.technical_standard_choice).click()
        time.sleep(1)
        self.find_element(*self.copy).click()
        time.sleep(1)
        self.find_element(*self.determine).click()
        time.sleep(2)